### ISSUE TITLE
problems need a fix

### ISSUE THREAD

**Issue by NexChill** [YuraBrm/BetterDiscordThemes#4]
i really love the theme but it doesn't seem working properly
<a href="https://i.imgur.com/4Q8IING.png">Issue 1</a>
<a href="https://i.imgur.com/EVa98xn.png">Issue 2</a>

**Comment by n3oney** [comment]
I have fixed it by adding background-color: transparent to some elements.
Add this code to the file: 
```css
.theme-dark .sidebarRegion-VFTUkN, .theme-dark .da-guildsWrapper, .theme-dark .contentRegion-3nDuYy, .theme-dark .standardSidebarView-3F1I7i, .theme-dark .container-3ayLPN, .channel-2QD9_O.selected-1HYmZZ a, .channel-2QD9_O:hover a, .theme-dark .gameLibrary-TTDw4Y, .ace-monokai, .ace-monokai, .theme-dark .user-settings-games .not-detected, .theme-light .user-settings-games .not-detected, .theme-dark .chat-3bRxxu, .theme-dark .chat-3bRxxu form, .theme-dark .content-yTz4x3, .theme-dark .messagesWrapper-3lZDfY, .theme-dark .messagesWrapper-3lZDfY.theme-dark .chat-3bRxxu, .theme-dark .chat-3bRxxu form, .theme-dark .content-yTz4x3, .videoBackgroundWrapper-2dCt49, .theme-dark .headerBar-UHpsPw, .theme-dark .header-1RC2Wb, .bda-dark .emoji-picker .category, .bda-dark .emojiPicker-3m1S-j .category-2U57w6, .emojiPicker-3m1S-j .stickyHeader-1SS0JU, .theme-dark .search-results-wrap .search-result .hit, .theme-dark .calendarPicker-2yf6Ci .react-datepicker, .theme-dark .search-results-wrap, .theme-dark .search-results-wrap .search-header, .theme-dark .search-results-wrap .channel-separator .channel-name, .theme-dark .calendarPicker-2yf6Ci .react-datepicker__header, .theme-dark .markup-2BOw-j pre, .theme-dark .menu-Sp6bN1, .theme-dark .header-ykumBX, .theme-dark .ui-standard-sidebar-view, .theme-dark .ui-standard-sidebar-view .content-region, .theme-dark .markup-2BOw-j code, .theme-dark .markup-2BOw-j code.inline, .container-PNkimc, .channels-Ie2l6A, .container-2lgZY8, .theme-dark .title-3qD0b-, .theme-dark .chat, .theme-dark .wrapper-29NfPK, .theme-dark .chat>.content, .theme-dark .chat form, .theme-dark .members-1998pB, .theme-dark .friends-table, .theme-dark .messages-wrapper, .theme-dark .activityFeed-28jde9, .theme-dark .headerNormal-T_seeN {
  background-color: transparent;
}
```
